-- 退宿申请表
CREATE TABLE IF NOT EXISTS `checkout_application` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `student_id` BIGINT NOT NULL COMMENT '学生ID',
  `check_in_application_id` BIGINT NOT NULL COMMENT '关联的入住申请ID',
  `building_id` BIGINT NOT NULL COMMENT '楼宇ID',
  `room_id` BIGINT NOT NULL COMMENT '房间ID',
  `bed_id` BIGINT NOT NULL COMMENT '床位ID',
  `reason` VARCHAR(50) NOT NULL COMMENT '退宿原因',
  `description` TEXT NOT NULL COMMENT '详细说明',
  `checkout_date` DATE NOT NULL COMMENT '预计退宿日期',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1-待审核 2-已同意 3-已驳回 4-已撤销',
  `approver_id` BIGINT NULL COMMENT '审批人ID',
  `approver_name` VARCHAR(50) NULL COMMENT '审批人姓名',
  `remark` VARCHAR(500) NULL COMMENT '审批意见',
  `approve_time` DATETIME NULL COMMENT '审批时间',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '0-未删除 1-已删除',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `idx_student_id` (`student_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='退宿申请表';

-- 换宿申请表
CREATE TABLE IF NOT EXISTS `transfer_application` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `student_id` BIGINT NOT NULL COMMENT '学生ID',
  `check_in_application_id` BIGINT NOT NULL COMMENT '关联的入住申请ID',
  `current_building_id` BIGINT NOT NULL COMMENT '当前楼宇ID',
  `current_room_id` BIGINT NOT NULL COMMENT '当前房间ID',
  `current_bed_id` BIGINT NOT NULL COMMENT '当前床位ID',
  `target_building_id` BIGINT NOT NULL COMMENT '目标楼宇ID',
  `target_room_id` BIGINT NOT NULL COMMENT '目标房间ID',
  `target_room_type` TINYINT NOT NULL COMMENT '目标房间类型：1-4人间 2-6人间',
  `reason` VARCHAR(50) NOT NULL COMMENT '换宿原因',
  `description` TEXT NOT NULL COMMENT '详细说明',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1-待审核 2-已同意 3-已驳回 4-已撤销 5-已完成',
  `approver_id` BIGINT NULL COMMENT '审批人ID',
  `approver_name` VARCHAR(50) NULL COMMENT '审批人姓名',
  `remark` VARCHAR(500) NULL COMMENT '审批意见',
  `approve_time` DATETIME NULL COMMENT '审批时间',
  `assigned_bed_id` BIGINT NULL COMMENT '管理员分配的床位ID',
  `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '0-未删除 1-已删除',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  INDEX `idx_student_id` (`student_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='换宿申请表';
